In [2]:
import pandas as pd
import numpy as numpy

In [3]:
df = pd.read_csv("women.csv")
df.head()

,State/union territory,No schooling,<5 years complete,5-7 years complete,8-9 years complete,10-11 years complete,12 or more years complete,Total,Percentage literate
0,India,22.6,5.2,13.4,17.8,15.2,25.9,100.0,71.5
1,Chandigarh,12.4,1.5,11.5,15.0,19.2,40.4,100.0,78.7
2,Delhi,13.1,2.7,9.6,14.9,16.3,43.4,100.0,83.7
3,Haryana,15.9,2.9,14.4,17.2,16.4,33.1,100.0,79.7
4,Himachal Pradesh,7.4,2.3,11.9,12.6,21.2,44.7,100.0,90.7

In [4]:
df = df.rename(columns={'Percentage literate': 'Percentage literate (women)'})
df.head()

,State/union territory,No schooling,<5 years complete,5-7 years complete,8-9 years complete,10-11 years complete,12 or more years complete,Total,Percentage literate (women)
0,India,22.6,5.2,13.4,17.8,15.2,25.9,100.0,71.5
1,Chandigarh,12.4,1.5,11.5,15.0,19.2,40.4,100.0,78.7
2,Delhi,13.1,2.7,9.6,14.9,16.3,43.4,100.0,83.7
3,Haryana,15.9,2.9,14.4,17.2,16.4,33.1,100.0,79.7
4,Himachal Pradesh,7.4,2.3,11.9,12.6,21.2,44.7,100.0,90.7

In [5]:
df1 = pd.read_csv("men.csv")
df1.head()

,State/union territory,No schooling,<5 years complete,5-7 years complete,8-9 years complete,10-11 years complete,12 or more years complete,Total,Percentage literate
0,India,10.7,6.3,13.0,19.8,18.0,32.2,100.0,84.4
1,Chandigarh,5.6,2.2,6.5,21.2,20.3,44.2,100.0,90.2
2,Delhi,6.8,2.7,9.4,20.3,19.4,41.5,100.0,90.2
3,Haryana,5.9,2.6,11.6,17.7,21.6,40.6,100.0,91.5
4,Himachal Pradesh,3.6,2.6,10.1,12.4,23.4,47.9,100.0,92.8

In [6]:
df1 = df1.rename(columns={'Percentage literate': 'Percentage literate (men)'})
df1.head()

,State/union territory,No schooling,<5 years complete,5-7 years complete,8-9 years complete,10-11 years complete,12 or more years complete,Total,Percentage literate (men)
0,India,10.7,6.3,13.0,19.8,18.0,32.2,100.0,84.4
1,Chandigarh,5.6,2.2,6.5,21.2,20.3,44.2,100.0,90.2
2,Delhi,6.8,2.7,9.4,20.3,19.4,41.5,100.0,90.2
3,Haryana,5.9,2.6,11.6,17.7,21.6,40.6,100.0,91.5
4,Himachal Pradesh,3.6,2.6,10.1,12.4,23.4,47.9,100.0,92.8

In [7]:
df3 = pd.merge(df,df1,on = "State/union territory")
df3.head()

,State/union territory,No schooling_x,<5 years complete_x,5-7 years complete_x,8-9 years complete_x,10-11 years complete_x,12 or more years complete_x,Total_x,Percentage literate (women),No schooling_y,<5 years complete_y,5-7 years complete_y,8-9 years complete_y,10-11 years complete_y,12 or more years complete_y,Total_y,Percentage literate (men)
0,India,22.6,5.2,13.4,17.8,15.2,25.9,100.0,71.5,10.7,6.3,13.0,19.8,18.0,32.2,100.0,84.4
1,Chandigarh,12.4,1.5,11.5,15.0,19.2,40.4,100.0,78.7,5.6,2.2,6.5,21.2,20.3,44.2,100.0,90.2
2,Delhi,13.1,2.7,9.6,14.9,16.3,43.4,100.0,83.7,6.8,2.7,9.4,20.3,19.4,41.5,100.0,90.2
3,Haryana,15.9,2.9,14.4,17.2,16.4,33.1,100.0,79.7,5.9,2.6,11.6,17.7,21.6,40.6,100.0,91.5
4,Himachal Pradesh,7.4,2.3,11.9,12.6,21.2,44.7,100.0,90.7,3.6,2.6,10.1,12.4,23.4,47.9,100.0,92.8

In [8]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State/union territory        37 non-null     object
 1   No schooling_x               37 non-null     float64
 2   <5 years complete_x          37 non-null     float64
 3   5-7 years complete_x         37 non-null     float64
 4   8-9 years complete_x         37 non-null     float64
 5   10-11 years complete_x       37 non-null     float64
 6   12 or more years complete_x  37 non-null     float64
 7   Total_x                      37 non-null     float64
 8   Percentage literate (women)  37 non-null     float64
 9   No schooling_y               37 non-null     float64
 10  <5 years complete_y          37 non-null     float64
 11  5-7 years complete_y         37 non-null     float64
 12  8-9 years complete_y         37 non-null     float64
 13  10-11 years complete_y       37 non-null     float64
 14  12 or more years complete_y  37 non-null     float64
 15  Total_y                      37 non-null     float64
 16  Percentage literate (men)    37 non-null     float64
dtypes: float64(16), object(1)
memory usage: 5.0+ KB

In [9]:
df3 = df3.drop(["No schooling_x","<5 years complete_x","5-7 years complete_x","8-9 years complete_x","10-11 years complete_x","12 or more years complete_x","Total_x","No schooling_y","<5 years complete_y","5-7 years complete_y","8-9 years complete_y","10-11 years complete_y","12 or more years complete_y","Total_y"],axis = 1)
df3 = df3.drop(0)
df3.head()

,State/union territory,Percentage literate (women),Percentage literate (men)
1,Chandigarh,78.7,90.2
2,Delhi,83.7,90.2
3,Haryana,79.7,91.5
4,Himachal Pradesh,90.7,92.8
5,Jammu & Kashmir,74.3,90.2

In [10]:
df3['Literacy Gap'] = df3['Percentage literate (men)'] - df3['Percentage literate (women)']
df3["Total Literacy"] = (df3['Percentage literate (men)']+df3['Percentage literate (women)'])/2
df3.head()

,State/union territory,Percentage literate (women),Percentage literate (men),Literacy Gap,Total Literacy
1,Chandigarh,78.7,90.2,11.5,84.45
2,Delhi,83.7,90.2,6.5,86.95
3,Haryana,79.7,91.5,11.8,85.60
4,Himachal Pradesh,90.7,92.8,2.1,91.75
5,Jammu & Kashmir,74.3,90.2,15.9,82.25

In [11]:
df3 = df3.drop(columns=["Percentage literate (women)","Percentage literate (men)","Literacy Gap"],axis = 1)
df3.head()

  State/union territory  Total Literacy
1            Chandigarh           84.45
2                 Delhi           86.95
3               Haryana           85.60
4      Himachal Pradesh           91.75
5       Jammu & Kashmir           82.25

In [12]:
df3 = df3.rename(columns = {"State/union territory":"State/UT"})
df3.head()

           State/UT  Total Literacy
1        Chandigarh           84.45
2             Delhi           86.95
3           Haryana           85.60
4  Himachal Pradesh           91.75
5   Jammu & Kashmir           82.25

In [13]:
df3.to_csv(r"C:\Users\Anish\OneDrive\Desktop\minor\DATA\lit.csv", index=False)#saved data