In [1]:
import pandas as pd

In [2]:
df5 = pd.read_csv("SDG6.csv")
df5

,Wealth and state/union territory,Type of sanitation Improved sanitation facility¹,Type of sanitation Shared facility²,Type of sanitation Unimproved sanitation facility³,Total,Percentage with basic sanitation service⁴,Percentage with limited sanitation service⁵
0,Wealth quintile,NaN,NaN,NaN,NaN,NaN,NaN
1,Lowest,37.5,10.6,51.9,100.0,37.5,5.8
2,Second,57.5,13.2,29.3,100.0,57.5,9.3
3,Middle,73.3,14.0,12.8,100.0,73.3,11.1
4,Fourth,86.9,10.6,2.5,100.0,86.9,8.6
5,Highest,95.6,4.2,0.1,100.0,95.6,3.2
6,State/union territory,NaN,NaN,NaN,NaN,NaN,NaN
7,India,70.2,10.5,19.3,100.0,70.2,7.6
8,North,NaN,NaN,NaN,NaN,NaN,NaN
9,Chandigarh,85.0,12.6,2.4,100.0,85.0,11.4
10,Delhi,81.1,17.7,1.2,100.0,81.1,13.3
11,Haryana,85.0,11.8,3.2,100.0,85.0,10.2
12,Himachal Pradesh,81.7,11.3,6.9,100.0,81.7,10.2
13,Jammu & Kashmir,75.7,18.7,5.6,100.0,75.7,3.1
14,Ladakh,42.3,57.2,0.5,100.0,42.3,1.1
15,Punjab,86.6,10.9,2.5,100.0,86.6,9.5
16,Rajasthan,71.1,7.1,21.8,100.0,71.1,5.8
17,Uttarakhand,78.7,15.0,6.3,100.0,78.7,14.0
18,Central,NaN,NaN,NaN,NaN,NaN,NaN
19,Chhattisgarh,76.8,8.9,14.3,100.0,76.8,6.1
20,Madhya Pradesh,65.1,10.0,24.9,100.0,65.1,7.5
21,Uttar Pradesh,68.7,9.1,22.2,100.0,68.7,7.4
22,East,NaN,NaN,NaN,NaN,NaN,NaN
23,Bihar,49.4,12.5,38.1,100.0,49.4,9.9
24,Jharkhand,56.7,10.4,32.9,100.0,56.7,6.2
25,Odisha,60.5,6.2,33.3,100.0,60.5,5.2
26,West Bengal,68.0,20.1,11.9,100.0,68.0,15.6
27,Northeast,NaN,NaN,NaN,NaN,NaN,NaN
28,Arunachal Pradesh,82.9,15.7,1.4,100.0,82.9,9.0
29,Assam,68.5,27.3,4.1,100.0,68.5,10.0
30,Manipur,64.9,34.8,0.4,100.0,64.9,29.9
31,Meghalaya,82.9,13.0,4.1,100.0,82.9,7.0
32,Mizoram,95.3,4.6,0.1,100.0,95.3,2.5
33,Nagaland,87.7,11.8,0.5,100.0,87.7,8.1
34,Sikkim,87.3,12.4,0.3,100.0,87.3,10.7
35,Tripura,73.6,25.4,1.1,100.0,73.6,15.1
36,West,NaN,NaN,NaN,NaN,NaN,NaN
37,Dadra & Nagar Haveli and Daman & Diu,65.8,24.0,10.3,100.0,65.8,NaN
38,Goa,87.9,8.6,3.4,100.0,87.9,7.3
39,Gujarat,74.0,6.1,19.9,100.0,74.0,3.3
40,Maharashtra,72.0,10.7,17.3,100.0,72.0,8.1
41,South,NaN,NaN,NaN,NaN,NaN,NaN
42,Andaman & Nicobar Islands,88.0,8.5,3.6,100.0,88.0,8.1
43,Andhra Pradesh,77.3,6.2,16.5,100.0,77.3,5.2
44,Karnataka,74.8,6.9,18.3,100.0,74.8,3.3
45,Kerala,98.7,1.1,0.2,100.0,98.7,0.5
46,Lakshadweep,99.8,0.2,0.0,100.0,99.8,0.1
47,Puducherry,84.9,5.2,9.9,100.0,84.9,4.0
48,Tamil Nadu,72.6,5.7,21.7,100.0,72.6,4.1
49,Telangana,76.2,12.2,11.5,100.0,76.2,9.4

In [3]:
df5 = df5.drop(["Type of sanitation Improved sanitation facility¹"	,"Type of sanitation Shared facility²"	,"Type of sanitation Unimproved sanitation facility³"	,"Total","Percentage with limited sanitation service⁵"],axis = 1)
df5

,Wealth and state/union territory,Percentage with basic sanitation service⁴
0,Wealth quintile,NaN
1,Lowest,37.5
2,Second,57.5
3,Middle,73.3
4,Fourth,86.9
5,Highest,95.6
6,State/union territory,NaN
7,India,70.2
8,North,NaN
9,Chandigarh,85.0
10,Delhi,81.1
11,Haryana,85.0
12,Himachal Pradesh,81.7
13,Jammu & Kashmir,75.7
14,Ladakh,42.3
15,Punjab,86.6
16,Rajasthan,71.1
17,Uttarakhand,78.7
18,Central,NaN
19,Chhattisgarh,76.8
20,Madhya Pradesh,65.1
21,Uttar Pradesh,68.7
22,East,NaN
23,Bihar,49.4
24,Jharkhand,56.7
25,Odisha,60.5
26,West Bengal,68.0
27,Northeast,NaN
28,Arunachal Pradesh,82.9
29,Assam,68.5
30,Manipur,64.9
31,Meghalaya,82.9
32,Mizoram,95.3
33,Nagaland,87.7
34,Sikkim,87.3
35,Tripura,73.6
36,West,NaN
37,Dadra & Nagar Haveli and Daman & Diu,65.8
38,Goa,87.9
39,Gujarat,74.0
40,Maharashtra,72.0
41,South,NaN
42,Andaman & Nicobar Islands,88.0
43,Andhra Pradesh,77.3
44,Karnataka,74.8
45,Kerala,98.7
46,Lakshadweep,99.8
47,Puducherry,84.9
48,Tamil Nadu,72.6
49,Telangana,76.2

In [4]:
df5 = df5.drop([0,1,2,3,4,5,6,7,8])
df5

,Wealth and state/union territory,Percentage with basic sanitation service⁴
9,Chandigarh,85.0
10,Delhi,81.1
11,Haryana,85.0
12,Himachal Pradesh,81.7
13,Jammu & Kashmir,75.7
14,Ladakh,42.3
15,Punjab,86.6
16,Rajasthan,71.1
17,Uttarakhand,78.7
18,Central,NaN
19,Chhattisgarh,76.8
20,Madhya Pradesh,65.1
21,Uttar Pradesh,68.7
22,East,NaN
23,Bihar,49.4
24,Jharkhand,56.7
25,Odisha,60.5
26,West Bengal,68.0
27,Northeast,NaN
28,Arunachal Pradesh,82.9
29,Assam,68.5
30,Manipur,64.9
31,Meghalaya,82.9
32,Mizoram,95.3
33,Nagaland,87.7
34,Sikkim,87.3
35,Tripura,73.6
36,West,NaN
37,Dadra & Nagar Haveli and Daman & Diu,65.8
38,Goa,87.9
39,Gujarat,74.0
40,Maharashtra,72.0
41,South,NaN
42,Andaman & Nicobar Islands,88.0
43,Andhra Pradesh,77.3
44,Karnataka,74.8
45,Kerala,98.7
46,Lakshadweep,99.8
47,Puducherry,84.9
48,Tamil Nadu,72.6
49,Telangana,76.2

In [5]:
df5 = df5.rename(columns={'Wealth and state/union territory': 'State/UT'})
df5 = df5.rename(columns={'Percentage with basic sanitation service⁴': 'Percentage with basic sanitation service'})
df5.head()

            State/UT  Percentage with basic sanitation service
9         Chandigarh                                      85.0
10             Delhi                                      81.1
11           Haryana                                      85.0
12  Himachal Pradesh                                      81.7
13   Jammu & Kashmir                                      75.7

In [6]:
df5.to_csv(r"C:\Users\Anish\OneDrive\Desktop\minor\DATA\san.csv", index=False)